export class PaymentSearchResult {
    constructor(
     // public paymentHistory: [Object],
      public installPaymentId: string,
      public billInstallmentId: string,
      public transactionDate: Date,
      public creditDate: Date,
      public apn: String,
      public sortAPN: String,
      public tracerNo: Number,
      public installNo: Number,
      public paymentStatus: String,
      public reason: String,
      public totalAmount: Number,
      public taxAmountPaid: Number,
      public penaltyAmount: Number,
      public interestAmount: Number,
      public costAmount: Number,
      public returnCheckFee: Number,
      public batchAgencyName: String,
      public paymentFiscalYear: String,
      public taxBillFiscalYear: String,
      public taxType: String,
      public batchNo: String,
      public tellerNo: String,
      public ncrSequenceNo: Number,
      public checkNo: Number,
      public paymentSource: String,
      public paymentMethod: String,
      public createdBy: String,
      public createdDate: Date,
      public hasAccessToPayCorrection: String,
      public hasAccessToReapply: String,
      public hasHistory: String,
        ) { }
  }

